# Generated by Django 5.1.4 on 2024-12-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burhanuddin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email_addr',
        ),
    ]
